# Generated by Django 5.2.1 on 2025-05-31 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ['-report_date'], 'verbose_name': 'Kunlik hisobot', 'verbose_name_plural': 'Kunlik hisobotlar'},
        ),
        migrations.AlterModelOptions(
            name='ingredientusagereport',
            options={'ordering': ['-report_date', 'ingredient__name'], 'verbose_name': 'Ingredient ishlatish hisoboti', 'verbose_name_plural': 'Ingredient ishlatish hisobotlari'},
        ),
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={'ordering': ['-report_month'], 'verbose_name': 'Oylik hisobot', 'verbose_name_plural': 'Oylik hisobotlar'},
        ),
        migrations.RenameIndex(
            model_name='dailyreport',
            new_name='idx_daily_report_date',
            old_name='unique_daily_report_date',
        ),
        migrations.RenameIndex(
            model_name='ingredientusagereport',
            new_name='idx_ingredient_usage_date',
            old_name='unique_ingredient_usage_date',
        ),
        migrations.RenameIndex(
            model_name='monthlyreport',
            new_name='idx_monthly_report',
            old_name='unique_monthly_report',
        ),
    ]
