# Generated by Django 5.2.1 on 2025-05-29 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(choices=[('STRING', 'Matn'), ('INTEGER', 'Butun son'), ('FLOAT', 'Haqiqiy son'), ('BOOLEAN', 'Mantiqiy'), ('JSON', 'JSON')], default='STRING', max_length=20)),
                ('is_editable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dastur sozlamasi',
                'verbose_name_plural': 'Dastur sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('DATABASE', "Ma'lumotlar bazasi"), ('REDIS', 'Redis'), ('CELERY', 'Celery'), ('EMAIL', 'Email'), ('STORAGE', 'Fayl saqlash'), ('API', 'API'), ('WEBSOCKET', 'WebSocket')], max_length=50)),
                ('status', models.CharField(choices=[('HEALTHY', "Sog'lom"), ('WARNING', 'Ogohlantirish'), ('ERROR', 'Xato'), ('DOWN', 'Ishlamayapti')], max_length=20)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tizim salomatligi',
                'verbose_name_plural': 'Tizim salomatligi yozuvlari',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_LOGIN', 'Foydalanuvchi kirdi'), ('USER_LOGOUT', 'Foydalanuvchi chiqdi'), ('USER_CREATED', 'Foydalanuvchi yaratildi'), ('USER_UPDATED', 'Foydalanuvchi yangilandi'), ('USER_DELETED', "Foydalanuvchi o'chirildi"), ('INGREDIENT_ADDED', "Mahsulot qo'shildi"), ('INGREDIENT_UPDATED', 'Mahsulot yangilandi'), ('INGREDIENT_DELETED', "Mahsulot o'chirildi"), ('DELIVERY_RECEIVED', 'Yetkazib berish qabul qilindi'), ('INVENTORY_ADJUSTED', 'Inventar tuzatildi'), ('MEAL_CREATED', 'Taom yaratildi'), ('MEAL_UPDATED', 'Taom yangilandi'), ('MEAL_DELETED', "Taom o'chirildi"), ('MEAL_SERVED', 'Taom berildi'), ('MEAL_CANCELLED', 'Taom bekor qilindi'), ('REPORT_GENERATED', 'Hisobot yaratildi'), ('NOTIFICATION_SENT', 'Bildirishnoma yuborildi'), ('ALERT_TRIGGERED', 'Ogohlantirish ishga tushdi'), ('SYSTEM_BACKUP', 'Tizim zaxirasi'), ('LOGIN_FAILED', 'Muvaffaqiyatsiz kirish'), ('PERMISSION_DENIED', 'Ruxsat berilmadi'), ('SUSPICIOUS_ACTIVITY', 'Shubhali faoliyat')], max_length=100)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faoliyat qayd etishi',
                'verbose_name_plural': 'Faoliyat qayd etishlari',
                'ordering': ['-timestamp'],
            },
        ),
    ]
