# Generated by Django 5.2.1 on 2025-05-29 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('subject_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bildirishnoma shabloni',
                'verbose_name_plural': 'Bildirishnoma shablonlari',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('browser_notifications', models.BooleanField(default=True)),
                ('low_stock_alerts', models.BooleanField(default=True)),
                ('waste_alerts', models.BooleanField(default=True)),
                ('meal_alerts', models.BooleanField(default=False)),
                ('report_alerts', models.BooleanField(default=True)),
                ('low_stock_threshold', models.FloatField(default=10.0)),
                ('notification_frequency', models.CharField(choices=[('REAL_TIME', 'Real vaqtda'), ('HOURLY', 'Har soatda'), ('DAILY', 'Har kuni'), ('WEEKLY', 'Har hafta')], default='REAL_TIME', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma sozlamasi',
                'verbose_name_plural': 'Bildirishnoma sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LOW_STOCK', 'Kam zaxira'), ('HIGH_WASTE', 'Yuqori chiqindi'), ('MEAL_READY', 'Ovqat tayyor'), ('MONTHLY_REPORT', 'Oylik hisobot'), ('SYSTEM_ALERT', 'Tizim ogohlantirishi'), ('EXPIRY_WARNING', 'Muddat ogohlantirishi')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('LOW', 'Past'), ('MEDIUM', "O'rta"), ('HIGH', 'Yuqori'), ('URGENT', 'Juda muhim')], default='MEDIUM', max_length=20)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='idx_notif_rec_read'), models.Index(fields=['type', 'created_at'], name='idx_notification_type_created')],
            },
        ),
    ]
