# Generated by Django 5.2.1 on 2025-06-03 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.PROTECT, to='accounts.role', verbose_name='Rol'),
        ),
    ]
