# Generated by Django 5.2.1 on 2025-05-29 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('meals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions_planned', models.IntegerField()),
                ('portions_served', models.IntegerField()),
                ('service_date', models.DateField()),
                ('service_time', models.TimeField()),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Nonushta'), ('LUNCH', 'Tushlik'), ('DINNER', 'Kechki ovqat'), ('SNACK', 'Yengil ovqat')], max_length=20)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('waste_quantity', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Rejalashtirilgan'), ('PREPARING', 'Tayyorlanmoqda'), ('READY', 'Tayyor'), ('SERVED', 'Berildi'), ('CANCELLED', 'Bekor qilindi')], default='PLANNED', max_length=20)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meal_services', to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='meals.meal')),
                ('served_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='served_meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ovqat xizmati',
                'verbose_name_plural': 'Ovqat xizmatlari',
            },
        ),
        migrations.CreateModel(
            name='ServiceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste_rating', models.IntegerField(blank=True, null=True)),
                ('portion_rating', models.IntegerField(blank=True, null=True)),
                ('overall_rating', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('meal_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='meal_service.mealservice')),
            ],
            options={
                'verbose_name': 'Xizmat bahosi',
                'verbose_name_plural': 'Xizmat baholari',
            },
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_planned', models.FloatField()),
                ('quantity_used', models.FloatField()),
                ('stock_before', models.FloatField()),
                ('stock_after', models.FloatField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('waste_quantity', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='inventory.ingredient')),
                ('meal_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='meal_service.mealservice')),
            ],
            options={
                'verbose_name': 'Xizmat qayd etish',
                'verbose_name_plural': 'Xizmat qayd etishlari',
            },
        ),
        migrations.AddIndex(
            model_name='mealservice',
            index=models.Index(fields=['service_date'], name='idx_mealservice_date'),
        ),
        migrations.AddIndex(
            model_name='mealservice',
            index=models.Index(fields=['served_by', 'served_at'], name='idx_mealservice_served_by_date'),
        ),
        migrations.AddIndex(
            model_name='servicelog',
            index=models.Index(fields=['meal_service', 'ingredient'], name='idx_svc_ing'),
        ),
    ]
