# Generated by Django 5.2.1 on 2025-05-31 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Zaxira tranzaksiyasi', 'verbose_name_plural': 'Zaxira tranzaksiyalari'},
        ),
    ]
